import { PaperPlaneIcon } from '@radix-ui/react-icons';
import Head from "next/head";
// import { useRouter } from 'next/navigation'
import { useState } from "react";

import ChatRoom from "@/components/ChatRoom";
import { Button } from "@/components/ui/button";
import { Input } from "@/components/ui/Input";

import { siteConfig } from "@/constant/config";
import { chatStore } from "@/lib/zustand/stores/chatStore";


const PortfolioPage = () => {
  const { messageData: chatData, set: setChatData } = chatStore();
  // const { getReplyData } = botStore();
  const [messageValue, setMessageValue] = useState('');

  // const { push: navigate } = useRouter();

  // const redirectToConfig = () => {
  //   navigate('config');
  // }

  const sendMessage = (e) => {

    if(e.key === 'Enter' || e.key === 'Click') {
      const messageData = {
        type: 'you',
        message: messageValue
      };
      setChatData(messageData);
      setMessageValue('');

      setTimeout(() => {
        console.log('🚀 ~ chatData:', chatData);
        // const replyData = getReplyData(chatData);
        // setChatData(replyData);
      }, 500);
    }
  }

  return (
    <>
      <Head>
        <title>Home - {siteConfig.title}</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
      </Head>

      <div className="h-full relative pt-6 px-2 pb-16 lg:grid lg:max-w-7xl lg:grid-rows-[auto,auto,1fr] lg:gap-x-8 lg:pb-24 lg:pt-5">
        <div className="w-full flex justify-center items-center mb-20">
          <img src="/images/logo.png" alt="simple-chat-logo" className="w-20" />
          <h3 className="text-base ps-2">Simple Chat.</h3>
        </div>

        {/* room chat */}
        <ChatRoom />

        {/* message input */}
        <div className="pt-5">
          <div className="flex absolute bottom-3 w-full pr-4 md:px-3">
            <Input value={messageValue} onChange={(e) => setMessageValue(e.target.value)} placeholder="Tulis pesan disini.." className="rounded-r-none" onKeyPress={(e) => sendMessage(e)} />
            <Button className="rounded-l-none" size="icon" onClick={() => sendMessage({key: 'Click'})}>
              <PaperPlaneIcon />
            </Button>
          </div>
        </div>
      </div>

      {/* <Dialog open={true}>
        <DialogContent className="sm:max-w-md">
          <DialogHeader>
            <DialogTitle>Hello :)</DialogTitle>
            <DialogDescription>
              Untuk memulai chat, tolong tambah config dulu ya.
            </DialogDescription>
          </DialogHeader>
          <DialogFooter className="sm:justify-start">
            <DialogClose>
              <Button type="button" onClick={redirectToConfig}>
                Tambah Config
              </Button>
            </DialogClose>
          </DialogFooter>
        </DialogContent>
      </Dialog> */}
    </>
  )
}


export default PortfolioPage;
